apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}-db-secret
  labels:
    {{- include "fastapiapp.labels" $ | nindent 4 }}
    app: {{ .Values.db.name }}-db
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.name }}_db_username
  POSTGRES_PASSWORD: {{ .Values.db.name }}_db_password
  POSTGRES_DB: {{ .Values.db.name }}_db_dev
  DATABASE_URI: postgresql://{{ .Values.db.name }}_db_username:{{ .Values.db.name }}_db_password@{{ .Values.db.name }}_db/{{ .Values.db.name }}_db_dev
