apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-db
  labels:
    {{- include "fastapiapp.labels" $ | nindent 4 }}
    app: {{ .Values.db.name }}-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "fastapiapp.selectorLabels" $ | nindent 4 }}
    app: {{ .Values.db.name }}-db